config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'dashboards#index'
  get 'static_pages/about'
  get 'static_pages/help'
  get 'static_pages/contact'
  resources :dashboards
  resources :invitations
  resources :invited_user_permissions, only: [:update]
  resources :boards do
    resources :lists do
      resources :notes
    end
  end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'registrations' }
  resources :profiles, only: [:show, :update, :edit]
  post 'user_boards', to: 'dashboards#create', as: 'user_boards'
  patch '/boards/:board_id/lists/:list_id/notes/:id/move', to: 'notes#move', as: :move
  patch '/notes/:board_id/:list_id/:note_id', to: 'notes#update_drop', as: :update_drop
  patch '/invitations', to: 'invitations#notificate', as: :notificate
  put '/boards/:board_id/lists/:id/switch_editability', to: 'lists#switch_editability', as: :switch_list_editability
  get '/lists/:id/allowed_actions', to: 'lists#allowed_actions', as: :list_allowed_actions
  get '/dashboards/:id/users/:user_id/join_user', to: 'dashboards#join_user'
  mount ActionCable.server => '/cable'
end

app/models/list.rb
# frozen_string_literal: true

class List < ApplicationRecord
  has_many :notes, dependent: :destroy
  belongs_to :board
  validates :title, presence: true
end

app/controllers/lists_controller.rb
# frozen_string_literal: true

class ListsController < ApplicationController
  before_action :set_current_list
  skip_before_action :set_current_list, only: :create
  before_action :check_creator_of_board, only: :switch_editability
  before_action :list_enabled?
  skip_before_action :list_enabled?, only: %i(create allowed_actions)

  respond_to :html, :js

  def create
    @list = List.new list_params
    @board = @list.board
    @note = Note.new
    @is_creator = current_user.id == @board.creator_id
    if @list.save
      list = render_to_string 'lists/_list', layout: false, locals: { list: @list }
      ActionCable.server.broadcast "lists_channel_#{params[:board_id]}", action: 'create', info: { list: list, id: @list.id }
    else
      redirect_to dashboards_path(params[:board_id]), flash: { alert: 'An error ocured while creating list' }
    end
  end

  def update
    if @list.update list_params
      ActionCable.server.broadcast "lists_channel_#{params[:board_id]}", action: 'update', info: { list_id: @list.id, title: @list.title }
    else
      flash[:alert] = 'An error ocured while updating list'
    end
  end

  def switch_editability
    @list.is_disabled = !@list.is_disabled
    @board = @list.board
    @note = Note.new
    @is_creator = current_user.id == @board.creator_id
    @lists = List.where board_id: params[:board_id]
    return unless @list.save
    list = render_to_string 'lists/_list_panel', layout: false, locals: { list: @list }
    ActionCable.server.broadcast "lists_channel_#{params[:board_id]}", action: 'switch_list_editability', info: { id: @list.id, list: list }
  end

  def destroy
    @list.destroy
    ActionCable.server.broadcast "lists_channel_#{params[:board_id]}", action: 'destroy', info: { id: @list.id }
  end

  def allowed_actions
    @board = @list.board
    Struct.new 'Actions', :hint, :icon_class, :method, :link_path, :data_toggle
    freeze = Struct::Actions.new 'freeze list', 'fa fa-ban', :put, switch_list_editability_path(@board, @list), nil
    freeze.hint = 'unfreeze list' if @list.is_disabled
    delete = Struct::Actions.new 'delete list', 'fa fa-times', nil, "#delete_list_#{@list.id}", 'modal'
    edit = Struct::Actions.new 'edit list', 'fa fa-pencil', nil, "#update_list_#{@list.id}", 'modal'
    actions = select_allowed_actions freeze, delete, edit
    respond_to do |format|
      format.js { render 'lists/allowed_actions', locals: { actions: actions, id: @list.id } }
    end
  end

  private

  def select_allowed_actions(freeze, delete, edit)
    actions = []
    actions.tap do |x|
    x << delete if @board.creator_id == current_user.id || !@list.is_disabled
    x << edit if @board.creator_id == current_user.id || !@list.is_disabled
    x << freeze if @board.creator_id == current_user.id
    end
  end

  def list_params
    params.require(:list).permit(:title, :is_disabled).merge(board_id: params['board_id'])
  end

  def check_creator_of_board
    redirect_to dashboard_path(params[:board_id]), flash: { warning: 'You have no permissions to perform this action' } unless current_user.id == @list.board.creator_id
  end

  def set_current_list
    @list = List.find_by id: params[:id]
    redirect_to dashboard_path(params[:id]), flash: { warning: 'List not found' } unless @list
  end

  def list_enabled?
    board = Board.find params[:board_id]
    redirect_to dashboard_path(params[:board_id]), flash: { warning: 'List is disabled!' } if @list.is_disabled && current_user.id != board.creator_id
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_action.html.haml
%li
  = link_to "#{action.link_path}", method: "#{action.method}", title: "#{action.hint}", 'data-toggle': "#{action.data_toggle}" do
    %div{class: "#{action.icon_class}"}

app/views/lists/_edit_list.html.haml
.modal.fade.bs-example-modal-sm{role: 'dialog', id: "update_list_#{modal_id}"}
  .modal-dialog.modal-sm
    .modal-content
      .modal-header
        %button{type: 'button', class: 'close', 'data-dismiss': 'modal'}
          &times;
        .text-center
          %h4
            Update list's title
      .modal-body
        .row
          .col-sm-offset-2
            = form_for list, remote: true, url: board_list_path(@board, list) do |f|
              .input-group.form-group
                = f.text_field :title, class: 'form-control col-xs-9', required: true, placeholder: "Note's content", autocomplete: 'off'
              = f.submit 'Update list', class: 'btn btn-primary col-xs-9'

app/views/lists/_list.html.haml
%div{id: "list_#{list.id}"}
  = render 'shared/delete_confirmation', object_type: 'list', path: board_list_path(@board, list), modal_id: "list_#{list.id}"
  = render 'lists/edit_list', modal_id: list.id, list: list
  = render 'lists/list_panel', list: list

app/views/lists/_list_form.html.haml
.col.col-md-12#new_list_form
  = form_for @list, remote: true, url: board_lists_path(@board, @list) do |f|
    .form-group
      = f.text_field :title, class: 'form-control', required: true, placeholder: "List's title", autocomplete: 'off', id: "new_list_title"
      - if can? :create, @list
        = f.submit @form_name, class: 'btn btn-success btn-block', id: "create-list_bord_id_#{@board.id}_user_id_#{current_user.id}"

app/views/lists/_list_panel.html.haml
.col.col-md-3
  .panel.panel-default.list-panel
    .panel-heading
      %span.list_title
        = list.title
      .dropdown.pull-right{list: "#{list.id}"}
        %a.dropdown-toggle{'data-toggle'=>'dropdown',
                            role: 'button',
                            'aria-haspopup'=>true,
                            'aria-expanded'=>false}
          .glyphicon.glyphicon-menu-hamburger.note_icon
        %ul.list_actions_menu{class: 'dropdown-menu', role: 'menu'}
          %li
            = link_to "#delete_list_#{list.id}", 'data-toggle'=>'modal' do
              .fa.fa-times
          %li
            = link_to "#update_list_#{list.id}", 'data-toggle'=>'modal' do
              .fa.fa-pencil
          %li
            = link_to switch_list_editability_path(@board, list), method: :put, remote: true do
              .fa.fa-ban
    .panel-body
      .list.scrollable
        = render partial: 'notes/note', collection: list.notes.order('created_at asc'), locals: {list: list}
      - unless list.is_disabled
        .list_footer
        - if can? :create, @note
          = render 'notes/note_form', list: list

app/views/lists/allowed_actions.js.erb
menu = $("#list_<%= id %> .list_actions_menu")
menu.html('<%= j (render partial: 'action', collection: actions)%>')
if (menu.html() == '')
  $('.dropdown[list=<%= id %>]').remove()