config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'dashboards#index'
  get 'static_pages/about'
  get 'static_pages/help'
  get 'static_pages/contact'
  resources :dashboards
  resources :invitations
  resources :invited_user_permissions, only: [:update]
  resources :boards do
    resources :lists do
      resources :notes
    end
  end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'registrations' }
  resources :profiles, only: [:show, :update, :edit]
  post 'user_boards', to: 'dashboards#create', as: 'user_boards'
  patch '/boards/:board_id/lists/:list_id/notes/:id/move', to: 'notes#move', as: :move
  patch '/notes/:board_id/:list_id/:note_id', to: 'notes#update_drop', as: :update_drop
  patch '/invitations', to: 'invitations#notificate', as: :notificate
  put '/boards/:board_id/lists/:id/switch_editability', to: 'lists#switch_editability', as: :switch_list_editability
  get '/lists/:id/allowed_actions', to: 'lists#allowed_actions', as: :list_allowed_actions
  get '/dashboards/:id/users/:user_id/join_user', to: 'dashboards#join_user'
  mount ActionCable.server => '/cable'
end

app/models/note.rb
# frozen_string_literal: true

class Note < ApplicationRecord
  belongs_to :list
  validates :text, presence: true
end

app/controllers/notes_controller.rb
# frozen_string_literal: true

class NotesController < ApplicationController
  before_action :set_current_note
  skip_before_action :set_current_note, only: [:create, :update_drop]
  before_action :list_enabled?
  load_and_authorize_resource

  def create
    note = Note.new note_params
    note.list_id = params[:list_id]
    if note.save
      ActionCable.server.broadcast "notes_channel_#{params[:board_id]}",
                                   note: render_note(note),
                                   list_id: params[:list_id],
                                   action: params[:action]
    else
      flash[:alert] = 'Error creating note'
    end
  end

  def destroy
    if @note.destroy
      ActionCable.server.broadcast "notes_channel_#{params[:board_id]}",
                                   action: params[:action],
                                   note_id: params[:id],
                                   list_id: params[:list_id]
    else
      flash[:alert] = 'Error destroying note'
    end
  end

  def update_drop
    note = Note.find(params[:note_id])
    @lists = List.where(board_id: params[:board_id])
    list = List.find(params[:list_id])
    @board = list.board
    render template: "notes/update_drop", locals: {note: note, list: list }
  end

  def update
    if @note.update note_params
      ActionCable.server.broadcast "notes_channel_#{params[:board_id]}",
                                   action: params[:action],
                                   note_id: params[:id],
                                   note_text: params[:note][:text]
    else
      flash[:alert] = 'Error updating note'
    end
  end

  def move
    note = Note.find params[:id]
    current_note_id = note.list_id
    @lists = List.where(board_id: params[:board_id])
    return unless note.update(list_id: params[:list_id])
    ActionCable.server.broadcast "notes_channel_#{params[:board_id]}",
                                 current_note_list_id: current_note_id,
                                 note: render_note(note),
                                 note_id: note.id,
                                 list_id: params[:list_id],
                                 action: params[:action]
  end

  private

  def render_note(note)
    @lists = List.where(board_id: params[:board_id])
    list = List.find(params[:list_id])
    @board = list.board
    render(partial: 'notes/note', locals: { note: note, list: list, board: @board, lists: @lists })
  end

  def note_params
    params.require(:note).permit(:text)
  end

  def set_current_note
    @note = Note.find_by id: params[:id]
    redirect_to dashboard_path(params[:board_id]), flash: { warning: 'Note not found' } unless @note
  end

  def list_enabled?
    list = @note ? @note.list : List.find(params[:list_id])
    board = list.board
    redirect_to dashboard_path(params[:board_id]), flash: { warning: 'List is disabled!' } if list.is_disabled && current_user.id != board.creator_id
  end
end

app/helpers/note_helper.rb
module NoteHelper
end

app/views/notes/_dropdown_move.html.erb
<% @lists.each do |list| %>
  <li>
    <% if(list.id != note.list_id) %>
      <%= link_to list.title,move_path(@board, list, note),method: :patch, remote: true, 'data-dismiss': 'modal' %>
    <% end %>
  </li>
<% end %>

app/views/notes/_edit_note.html.haml
.modal.bs-example-modal-sm.edit_notes{role: 'dialog', id: "edit_notes_#{note.id}"}
  .modal-dialog
    .modal-content
      .modal-header
        %button{type: 'button', class: 'close', 'data-dismiss': 'modal'}
          &times;
        .text-center
          %h4
            Update note
      .modal-body
        .row
          .col-sm-offset-2
            = form_for note,remote:'true', url: board_list_note_path(@board, list, note) do |f|
              .input-group.form-group
                = f.text_area :text, class: 'form-control col-xs-9', required: true, placeholder: "Edit note", autocomplete: 'off', cols: 40, rows: 4
              = f.submit 'Update note', class: 'btn btn-primary col-xs-9 edit_note_button'

app/views/notes/_move_note.html.haml
.modal.bd-example-modal-sm{role: 'dialog', id: "move_note_#{modal_id}"}
  .modal-dialog.modal-sm
    .modal-content
      .modal-header
        %button{type: 'button', class: 'close', 'data-dismiss': 'modal'}
          &times;
        .text-center
          %h4
            Move note to another list
      .modal-body
        .dropdown
          .text-center
            .btn-group
              = link_to 'Choose list', update_drop_path(@board, list, note), method: :patch, class: 'btn dropdown-toggle', 'data-toggle': 'dropdown', remote: 'true'
              %ul.dropdown-menu.dropdown_note.dropdown_move
                - @lists.each do |list|
                  %li
                    - if(list.id != note.list_id)
                      = link_to list.title,move_path(@board, list, note),method: :patch, remote: true, 'data-dismiss': 'modal'

app/views/notes/_note.html.haml
= render 'shared/delete_confirmation', object_type: 'note', path: board_list_note_path(@board, list, note), modal_id: note.id
= render 'notes/edit_note', note: note, list: list
= render 'notes/move_note', note: note, modal_id: "#{note.id}", list: list
.panel.panel-default.note_panel{id: "note_#{note.id}"}
  - if !list.is_disabled
    .col-sm-12
      .dropdown.pull-right
        %a.dropdown-toggle{'data-toggle'=> 'dropdown', role: 'button', 'aria-haspopup'=>'true', 'aria-expanded'=>'false'}
          .glyphicon.glyphicon-menu-hamburger.note_icon
        %ul{class: 'dropdown-menu', role: 'menu', id: "note_menu"}
          %li
            - if can? :destroy, note
              = link_to "#delete_#{note.id}", 'data-toggle': 'modal',title: "delete note" do
                .fa.fa-times
          %li
            - if can? :update, note
              = link_to "#edit_notes_#{note.id}", 'data-toggle': 'modal', title: "edit note" do
                .fa.fa-pencil
          %li
            - if can? :move, note
              = link_to "#move_note_#{note.id}", 'data-toggle': 'modal', title: "move note" do
                .fa.fa-location-arrow
  .panel-body.scrollable.note
    %pre
      %span.content_for_update= note.text

app/views/notes/_note_form.html.haml
.center-block
  = form_for @note,remote: true, url: board_list_notes_path(@board, list, @note) do |f|
    .form-group
      = f.text_area :text, class: 'form-control', required: true, placeholder: "New note", size: 'auto x2', autocomplete: 'off'
      - if can? :create, @note
        = f.submit @form_name, class: 'btn btn-success btn-block', disabled: list.is_disabled

app/views/notes/update_drop.js.erb
$('.dropdown_move').html("<%= j render(partial: 'notes/dropdown_move', locals: {note: note, list: list}) %>");