config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'dashboards#index'
  get 'static_pages/about'
  get 'static_pages/help'
  get 'static_pages/contact'
  resources :dashboards
  resources :invitations
  resources :invited_user_permissions, only: [:update]
  resources :boards do
    resources :lists do
      resources :notes
    end
  end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'registrations' }
  resources :profiles, only: [:show, :update, :edit]
  post 'user_boards', to: 'dashboards#create', as: 'user_boards'
  patch '/boards/:board_id/lists/:list_id/notes/:id/move', to: 'notes#move', as: :move
  patch '/notes/:board_id/:list_id/:note_id', to: 'notes#update_drop', as: :update_drop
  patch '/invitations', to: 'invitations#notificate', as: :notificate
  put '/boards/:board_id/lists/:id/switch_editability', to: 'lists#switch_editability', as: :switch_list_editability
  get '/lists/:id/allowed_actions', to: 'lists#allowed_actions', as: :list_allowed_actions
  get '/dashboards/:id/users/:user_id/join_user', to: 'dashboards#join_user'
  mount ActionCable.server => '/cable'
end

app/views/shared/_chat.html.haml
.col.col-md-12
  .panel.panel-primary#block_for_chat
    .panel-heading
      %span.glyphicon.glyphicon-comment
      Chat
    .panel-body
      .chat.scrollable
        %left.clearfix
          .chat-body.clearfix
            .header
              %strong.primary-font
                #messages
                  = render @messages
              %small.pull-right.text-muted
    .panel-footer
      - if can? :create_message, @board
        %input#btn-input.form-control.input-sm{"data-behavior" => "room_speaker", :type => "text", id: "chat-board_id_#{@board.id}_user_id_#{current_user.id}"}/

app/views/shared/_delete_confirmation.html.haml
.modal.bs-example-modal-sm{role: 'dialog', id: "delete_#{modal_id}"}
  .modal-dialog.modal-sm
    .modal-content
      .modal-header
        %button{type: 'button', class: 'close', 'data-dismiss': 'modal'}
          &times;
        .text-center
          %h4
            Confirm removing
      .modal-body
        .text-center
          %p= "Are sure to remove this #{object_type}?"
      .modal-footer
        .btn.btn-success{'data-dismiss': 'modal'}
          Cancel
        %a.btn.btn-danger{href: path, 'data-method': 'delete','data-dismiss':'modal', 'data-remote'=>true, rel: 'nofollow'}
          Confirm

app/views/shared/_dropdown_for_users.html.erb
<div class="modal fade" id="user<%= user.id %>" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">User information</h4>
      </div>
      <div class="modal-body">
      <% if board_creator? current_user %>
        <%= form_for user_permission(@board, user) do |f| %>
          <%= hidden_field_tag :board_id, @board.id %>
          <%= hidden_field_tag :user_id, user.id %>
          <% InvitedUserPermission::PERMITTABLE_FIELDS.each do |field_name| %>
            <p>
              <%= f.check_box field_name %>
              <%= field_name %>
            </p>
          <% end %>
          <%= f.submit %>
        <% end %>
      <% end %>
      </div>
      <div class="modal-footer">
        <%= link_for_creator(user) %>
        <%= link_for_subscriber(user) %>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

app/views/shared/_dropdown_menu.html.erb
<%= link_to "#", 'data-toggle': 'dropdown' do %>
  <div class="btn btn-primary dropdown-toggle" >
    Joined users
    <span class="caret"></span></button>
  </div>
<% end %>
<ul class="dropdown-menu joined_users">
  <% @board.users.each do |user| %>
    <%= render 'boards/joined_user', user: user%>
  <% end %>
</ul>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Trellogram", root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "About"  , static_pages_about_path %></li>
        <!-- <li><%= link_to "Admin" , rails_admin_path %></li> -->
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% unless user_signed_in? %>
          <li>
            <%= link_to new_user_session_path do %>
              <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>
              <span> Login</span>
            <% end %>
          </li>
        <% else %>
          <li class="dropdown">
            <a href="/invitations" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" data-method="patch" data-remote="true" >
              <%= current_user.email %> <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to profile_path(current_user) do %>
                  <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                  <span> Profile</span>
                <% end %>
              </li>
              <li class='notification'>
                <a href="<%= invitations_path %>">
                  <span class="badge"><%= @invitation_count %></span>
                  <span> Invites</span>
                </a>
              </li>
              <li role="separator" class="divider"></li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
                  <span> Logout</span>
                <% end %>
              </li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_invitation_form.html.erb
<div class="thumbnail">
  <div class="caption">
    <%= form_for("send", method: "post") do |f| %>
      <div class="form-group">
        <%=f.text_field :board_title, class: "form-control", placeholder: "Board name", required: true, autocomplete: 'off' %>
      </div>
      <div class="form-group">
        <%= f.email_field :inviting_user, class: "form-control" ,size: "auto x2", placeholder:"Email" ,required: true, autocomplete: 'off' %>
      </div>
      <%= f.submit "Send",class: "btn btn-success btn-block" %>
    <% end %>
  </div>
</div>

app/views/shared/_inviting_create_form.html.haml
.container
  .input_form
    %h1= @form_name
    = form_for(@inviting) do |f|
      .col-sm-3
        .form-group
          = f.text_field :user_to_invite_id, class: 'form-control', required: true,placeholder: "email"
          = f.submit @form_name, class: 'btn btn-success btn-block'

app/views/shared/_list.html.erb
<div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">  
     <div class="caption"> 

      <div class="right">
        <a href="#" class="glyphicon glyphicon-remove"></a>
      </div>
      <h3>Title List</h3> 

          <%= render "shared/note" %>
      <p><a href="#" class="btn btn-primary" role="button">Create note</a> 
    </div>



    </div>
  </div>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">  
      <div class="caption"> 
        <div class="center">
          <p><a href="#" class="btn btn-primary" role="button">Create list</a> </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_list_form.html.haml
= form_for @list do |f|
  .col-md-2
    .form-group
      = f.text_field :title, class: 'form-control', required: true, placeholder: "List's title"
      = f.submit @form_name, class: 'btn btn-success btn-block'

app/views/shared/_menu_bar.html.erb
<%= render 'shared/delete_confirmation', object_type: 'board', modal_id: @board.object_id, path: board_path(@board) %>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#"><%= @board.title %></a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li>
        <%= render 'shared/dropdown_menu' %>
      </li>
      <% if @board.creator_id == current_user.id %>
        <li class='menu-button'>
          <%= link_to "#delete_#{@board.object_id}",  'data-toggle': 'modal' do %>
            <div class='btn btn-danger'>Delete board</div>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/shared/_note.html.erb
    <div class="alert alert-info">
      <div class="right">
        <a href="#" class="glyphicon glyphicon-remove"></a>
      </div>
        <h4>Title note</h4>
        <h5>Description note</h5>
      </div>

app/views/shared/_notificate.html.erb
<a href="<%= invitations_path %>">
  <span class="badge"><%= @invitation_count %></span>
  <span> Invite</span>
</a>

app/views/shared/notificate.js.erb
$('.notification').html("<%= j render(partial: 'shared/notificate') %>")