config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'dashboards#index'
  get 'static_pages/about'
  get 'static_pages/help'
  get 'static_pages/contact'
  resources :dashboards
  resources :invitations
  resources :invited_user_permissions, only: [:update]
  resources :boards do
    resources :lists do
      resources :notes
    end
  end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'registrations' }
  resources :profiles, only: [:show, :update, :edit]
  post 'user_boards', to: 'dashboards#create', as: 'user_boards'
  patch '/boards/:board_id/lists/:list_id/notes/:id/move', to: 'notes#move', as: :move
  patch '/notes/:board_id/:list_id/:note_id', to: 'notes#update_drop', as: :update_drop
  patch '/invitations', to: 'invitations#notificate', as: :notificate
  put '/boards/:board_id/lists/:id/switch_editability', to: 'lists#switch_editability', as: :switch_list_editability
  get '/lists/:id/allowed_actions', to: 'lists#allowed_actions', as: :list_allowed_actions
  get '/dashboards/:id/users/:user_id/join_user', to: 'dashboards#join_user'
  mount ActionCable.server => '/cable'
end

app/models/invitation.rb
# frozen_string_literal: true

class Invitation < ApplicationRecord
  validate :invitor_id_not_equal_user_to_invite, :uniq_invite, :uniq_user_invite
  belongs_to :invitor, class_name: 'User'
  belongs_to :user_to_invite, class_name: 'User'
  belongs_to :board

  def invitor_id_not_equal_user_to_invite
    if self.invitor_id == self.user_to_invite_id
      errors.add(:invitor_id, "can't be equal user ")
    end
  end

  def uniq_invite
    count_of_equal_invite = Invitation.where(board_id: self.board_id, user_to_invite_id: self.user_to_invite_id).count
    errors.add(:invite, 'must be uniq') if count_of_equal_invite.positive?
  end

  def uniq_user_invite
    user_to_invite = User.find(self.user_to_invite_id)
    user_to_invite_boards = user_to_invite.boards
    if user_to_invite_boards.ids.include?(self.board_id)
      errors.add(:user_to_invite, 'must be uniq')
    end
  end
end

app/controllers/invitations_controller.rb
# frozen_string_literal: true

class InvitationsController < ApplicationController
  authorize_resource
  skip_authorize_resource only: [:index, :create]
  before_action :user_email_presence, only: :create

  def index
    @invite = Invitation.where(user_to_invite_id: current_user.id)
  end

  def create
    @invitation = Invitation.new(prepare_params)
    if @invitation.save
      flash[:success] = 'inviting successfuly was sent'
    else
      flash[:warning] = @invitation.errors.messages.to_s
    end
      redirect_to invitations_path
  end

  def destroy
    invite_id = params[:id]
    @invite = Invitation.find(invite_id).destroy
    redirect_to invitations_path
  end

  private

  def prepare_params
    board_title = params[:send][:board_title].chomp
    inviting_user = params[:send][:inviting_user].chomp
    invitor_id = current_user.id
    board_id = current_user.boards.find_by(title: board_title).id
    user_to_invite_id = User.find_by(email: inviting_user).id
    { board_id: board_id, invitor_id: invitor_id, user_to_invite_id: user_to_invite_id }
  end

  def user_email_presence
    unless User.find_by(email: params[:send][:inviting_user])
      flash[:warning] = "this user don't exist"
      redirect_to invitations_path
    end
  end
end

app/views/invitations/_invitation_create_form.html.haml
.container
  .input_form
    %h1= @form_name
    = form_for(@invitation) do |f|
      .col-sm-3
        .form-group
          = f.text_field :user_to_invite_id, class: 'form-control', required: true,placeholder: "email"
          = f.submit @form_name, class: 'btn btn-success btn-block'

app/views/invitations/_invitation_form.html.erb
<div class="thumbnail">
  <div class="caption">
    <%= form_for("send", method: "post") do |f| %>
      <div class="form-group">
        <%= f.label :choose_board %>
        <%= f.select :board_title, current_user.boards.all.collect { |p|  p.title },{},{class: "form-control"} %>
      </div>
      <div class="form-group">
        <%= f.label :choose_user_by_email %>
        <%= f.email_field :inviting_user, class: "form-control",size: "auto x2",placeholder:"Email",required:true %>
      </div>
      <%= f.submit "Send",class: "btn btn-success btn-block" %>
    <% end %>
  </div>
</div>

app/views/invitations/_invite_form.html.erb
  <div class="thumbnail">
    <div class="caption">
      <%= form_for("send", method: "post") do |f| %>
        <div class="form-group">
          <%=f.text_field :board_title, class: "form-control",placeholder:"Board name",required:true %>
        </div>
        <div class="form-group">
          <%= f.text_area :inviting_user, class: "form-control",size: "auto x2",placeholder:"Email",required:true %>
        </div>
        <%= f.submit "Send",class: "btn btn-success btn-block" %>
      <% end %>
    </div>
  </div>

app/views/invitations/index.html.erb
<div class="container">
  <div class="row" >
    <div class="col-sm-6" >
      <div class="panel panel-default">
        <div class="panel-heading">List of invites</div>
      </div>
    <div class='table-responsive'>
      <table class="table">
        <thead>
          <tr>
            <th>Board name</th>
            <th>Email</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @invite.each do |i| %>
            <tr>
              <td><%= Board.find(i.board_id).title %></td>
              <td><%= User.find(i.invitor_id).email %></td>
              <td>
                <%= link_to "Confirm", user_boards_path(board_id: i.board_id), method: :post, class:"btn btn-success" %>
              </td>
              <td>
                <%= link_to "Reject", invitation_path(i), method: :delete, class:"btn btn-danger" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    </div>
    <div class="col-sm-4" >
      <div class="panel panel-default">
        <div class="panel-heading">Invite</div>
      </div>
      <%= render 'invitations/invitation_form' %>
    </div>
    <div class="col-sm-4" >
    </div>
  </div>
</div>